language: go

services:
  - postgresql

before_script:
  - psql -c 'create database nestor;' -U postgres
  - psql -c 'create user nestor password \'nestor\';' -U postgres
  - psql -c 'grant all on nestor to nestor;' -U postgres